---
- name: Undeploy Webserver on VM1 and VM2
  hosts: all
  become: yes

  tasks:
    - name: Stop Apache service
      service:
        name: apache2
        state: stopped

    - name: Disable Apache service
      service:
        name: apache2
        enabled: no

    - name: Uninstall Apache
      apt:
        name: apache2
        state: absent
